# Generated by Django 2.2.6 on 2019-10-22 18:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField(help_text='Your note goes here, YO')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 10, 22, 18, 47, 23, 336984, tzinfo=utc))),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
