# Generated by Django 2.2.6 on 2019-10-22 21:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='body',
        ),
        migrations.AddField(
            model_name='note',
            name='description',
            field=models.TextField(blank=True, help_text='Put your shit here.', null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
